#!/usr/bin/env sh

yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four

yabai -m config layout bsp

yabai -m config window_shadow float

yabai -m config window_border off
yabai -m config window_border_width 4
yabai -m config window_border_radius -1.0
yabai -m config active_window_border_color 0xff282828
yabai -m config normal_window_border_color 0xff282828

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 resize
yabai -m config mouse_action2 move


yabai -m config top_padding    50
yabai -m config bottom_padding 50
yabai -m config left_padding   50
yabai -m config right_padding  50
yabai -m config window_gap     10

# float system preferences
yabai -m rule --add app="^System Preferences$" manage=off

# floating windows are always on top (default: off)
yabai -m config window_topmost on

yabai -m config auto_balance off
yabai -m config split_ratio 0.3

yabai -m config window_placement second_child
